[build-system]
requires = ["hatchling", "imutils", "numpy", "opencv-python", "pydoc-markdown", "mypy", "flake8", "pytest"]
build-backend = "hatchling.build"

[project]
name = "gcode2dplotterart"
version = "0.0.4"
authors = [
  { name="Travis Bumgarner", email="travis@sillysideprojects.com" },
]
description = "Easily generate plotter art with your 2D Plotter or 3D Printer. This library abstracts away G-Code so you can focus on making art."
readme = "README.md"
requires-python = ">=3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/TravisBumgarner/gcode2dplotterart"
"Bug Tracker" = "https://github.com/TravisBumgarner/gcode2dplotterart/issues"
